name: PyNinja CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        if [ -d "tests" ]; then
          python -m unittest discover -s tests
        else
          echo "No tests directory found."
        fi

    - name: Validate PyNinja
      run: |
        python validate_package.py

    - name: Show version
      run: |
        pyninja --version
